#!/bin/sh
g++ -std=c++11 -c -I./lib/ ./src/Order.cpp -o ./out/Order.o && \
g++ -std=c++11 -c -I./lib/ ./src/Customer.cpp -o ./out/Customer.o && \
g++ -std=c++11 -c -I./lib/ ./src/Ordering.cpp -o ./out/Ordering.o && \
g++ ./out/Order.o ./out/Customer.o ./out/Ordering.o -o Ordering && \
echo "Compiled Successfully!" || echo "There was an error!"

