#!/bin/sh
function compile() {
    g++ -std=c++11 -c -I./lib/ ./src/$1.cpp -o ./out/$1.o 
}

compile Order && \
compile Customer && \
compile Ordering && \
g++ ./out/Order.o ./out/Customer.o ./out/Ordering.o -o ordering && \
echo "Compiled Successfully!" || echo "There was an error!"

